services:
  alice:
    image: krisbit/zenchain-testnet
    ports:
      - "9944:9944"
      - "9615:9615"
    command:
      - "./usr/bin/zenchain-node"
      - "--node-key=0000000000000000000000000000000000000000000000000000000000000001"
      - "--base-path=/tmp/alice"
      - "--chain=local"
      - "--port=30333"
      - "--validator"
      - "--alice"
      - "--bootnodes=/dns/bob/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
      - "--unsafe-rpc-external"
      - "--log=sub-libp2p=trace"
      - "--rpc-cors=all"

  bob:
    image: krisbit/zenchain-testnet
    ports:
      - "9945:9944"
    command:
      - "./usr/bin/zenchain-node"
      - "--node-key=0000000000000000000000000000000000000000000000000000000000000002"
      - "--base-path=/tmp/bob"
      - "--chain=local"
      - "--port=30333"
      - "--validator"
      - "--bob"
      - "--bootnodes=/dns/alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--rpc-cors=all"
      - "--unsafe-rpc-external"
      - "--log=sub-libp2p=trace"

  dave:
    image: krisbit/zenchain-testnet
    ports:
      - "9946:9944"
    command:
      - "./usr/bin/zenchain-node"
      - "--node-key=0000000000000000000000000000000000000000000000000000000000000003"
      - "--base-path=/tmp/light"
      - "--chain=local"
      - "--port=30333"
      - "--bootnodes=/dns/alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--bootnodes=/dns/bob/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
      - "--rpc-cors=all"
      - "--unsafe-rpc-external"
      - "--log=sub-libp2p=trace"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  webdis:
    image: nicolas/webdis:latest
    command: /usr/local/bin/webdis /webdis/webdis.json
    volumes:  # mount volume containing the config file
      - ./webdis:/webdis
    container_name: webdis
    ports:
      - "7379:7379"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  nft-sleep-mint-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nft-sleep-mint-bot
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379/
    ports:
      - "3000:3000"
    depends_on:
      - alice
      - bob
      - dave
      - webdis

volumes:
  redis-data: